// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.lvchao.dfs.namenode.rpc.model;

public interface FetchEditsLogRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lvchao.dfs.namenode.rpc.FetchEditsLogRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 syncedTxid = 1;</code>
   */
  long getSyncedTxid();
}
