// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.lvchao.dfs.namenode.rpc.model;

public interface RegisterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lvchao.dfs.namenode.rpc.RegisterResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 status = 1;</code>
   */
  int getStatus();
}
